[package]
name = "rls"
version = "0.1.0"
authors = ["Unnikrishnan Nair, Rahul <rahul.unnikrishnan.nair@intel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
